# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Frames
version:      0.03
version_from: lib/WWW/Mechanize/Frames.pm
installdirs:  site
requires:
    Clone::PP:                     0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
